name: beleza
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.5  # Versão mais recente (ou a mais compatível)
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.0 # Dependência para o calendário
  intl: ^0.18.0 # Dependência para lidar com formatação de data/hora
  mysql1: ^0.20.0 # Atualizando a dependência para a versão mais recente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
